#!/usr/bin/env python3
import argparse
import csv
import json
from datetime import datetime
from pathlib import Path

import psycopg2
from psycopg2 import sql
from psycopg2.extras import Json, RealDictCursor


def sanitize_name(name: str) -> str:
    return name.replace('"', '').replace('/', '_')


def main() -> int:
    parser = argparse.ArgumentParser(description="Export full PostgreSQL DB data and schema metadata")
    parser.add_argument("--url", required=True, help="PostgreSQL connection URL")
    parser.add_argument("--out", default="backups", help="Output base folder")
    args = parser.parse_args()

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_dir = Path(args.out) / f"render_db_export_{ts}"
    data_dir = out_dir / "data"
    out_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)

    conn = psycopg2.connect(args.url)
    conn.autocommit = True

    with conn, conn.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute(
            """
            SELECT table_schema, table_name
            FROM information_schema.tables
            WHERE table_type = 'BASE TABLE'
              AND table_schema NOT IN ('pg_catalog', 'information_schema')
            ORDER BY table_schema, table_name
            """
        )
        tables = cur.fetchall()

        cur.execute(
            """
            SELECT table_schema, table_name, column_name, ordinal_position, data_type, is_nullable
            FROM information_schema.columns
            WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
            ORDER BY table_schema, table_name, ordinal_position
            """
        )
        columns = cur.fetchall()

        schema_meta = {
            "exported_at": datetime.now().isoformat(),
            "tables": tables,
            "columns": columns,
        }
        (out_dir / "schema_metadata.json").write_text(json.dumps(schema_meta, indent=2), encoding="utf-8")

        insert_sql_path = out_dir / "data_inserts.sql"
        with insert_sql_path.open("w", encoding="utf-8") as sql_file:
            sql_file.write("-- Data-only SQL export generated by db_full_export.py\n")
            sql_file.write("BEGIN;\n")

            manifest = []
            for t in tables:
                schema = t["table_schema"]
                table = t["table_name"]
                safe = f"{sanitize_name(schema)}.{sanitize_name(table)}"

                cur.execute(
                    sql.SQL("SELECT * FROM {}.{}").format(
                        sql.Identifier(schema),
                        sql.Identifier(table),
                    )
                )
                rows = cur.fetchall()

                json_path = data_dir / f"{safe}.json"
                json_path.write_text(json.dumps(rows, indent=2, default=str), encoding="utf-8")

                if rows:
                    csv_path = data_dir / f"{safe}.csv"
                    with csv_path.open("w", newline="", encoding="utf-8") as f:
                        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
                        writer.writeheader()
                        writer.writerows(rows)

                    col_names = list(rows[0].keys())
                    col_ident_list = sql.SQL(", ").join([sql.Identifier(c) for c in col_names])
                    for row in rows:
                        values = []
                        for c in col_names:
                            v = row[c]
                            if isinstance(v, (dict, list)):
                                values.append(Json(v))
                            else:
                                values.append(v)
                        value_literals = sql.SQL(", ").join(sql.Literal(v) for v in values)
                        stmt = sql.SQL("INSERT INTO {}.{} ({}) VALUES ({});").format(
                            sql.Identifier(schema),
                            sql.Identifier(table),
                            col_ident_list,
                            value_literals,
                        )
                        sql_file.write(stmt.as_string(conn) + "\n")

                manifest.append(
                    {
                        "schema": schema,
                        "table": table,
                        "rows": len(rows),
                        "json": str(json_path),
                    }
                )
                print(f"Exported {schema}.{table}: {len(rows)} rows")

            sql_file.write("COMMIT;\n")

        (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    conn.close()
    print(f"\nExport complete: {out_dir}")
    print("Includes: schema_metadata.json, data/*.json, data/*.csv, data_inserts.sql, manifest.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
